### ISSUE TITLE
Publish in F-Droid FOSS app catalog

### ISSUE THREAD

**Issue by ix5** [jruesga/rview#101]
The F-Droid project encompasses both an app catalog of FOSS Android applications and an app to view, download and install them. They only accept fully open source applications under a free license, with no proprietary parts allowed.
See the [FAQ for developers](https://f-droid.org/en/docs/FAQ_-_App_Developers/).

I think you did a stellar job with `rview` @jruesga and it would be a welcome addition to the F-Droid app catalog. However, there are some tweaks needed to get it into the right shape.

There'd have to be a way to turn off all proprietary libraries for a FOSS build lest the app submission violates the [Inclusion Policy](https://f-droid.org/en/docs/Inclusion_Policy/)
So far I see in [build.gradle](https://github.com/jruesga/rview/blob/master/build.gradle):
- `play_services_auth`
- `firebase_core`
- `firebase_messaging`
- `crashlytics`
- `crashlytics_core`
- `crashlytics_answers`

@jruesga would you be willing to work with me on this? I'd be happy to handle the metadata side and deal with the F-Droid people.

Since I'm a Java/Android app novice, a bit of help regarding build polymorphism would be appreciated. So far I've taken a look at how syncthing handles Google Play vs F-Droid releases, seems like a good starting point: https://github.com/syncthing/syncthing-android/blob/master/app/build.gradle

**Comment by jruesga** [comment]
https://github.com/jruesga/rview/commit/4264f20cd3d390317e055cc6b72d697e2edfdaa7 brings support for building both, GMS and and FLOSS flavors. The first one is the one that will be released to the PlayStore. The other flavor is for anyone that want to run Rview without Firebase and Google Services.

@ix5 you can publish to f-droid once I tagged the next release.

**Comment by chirayudesai** [comment]
@ix5 Did you ever submit this to F-Droid?

**Comment by ix5** [comment]
WIP MR submitted to F-Droid GitLab: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/7538
