### ISSUE TITLE
Ability to view "CCed on" changes

### ISSUE THREAD

**Issue by vmiklos** [jruesga/rview#107]
Hi,

First, thanks for this great app!

I primarily use it against a gerrit server that got upgraded to 3.x recently, which means there is a new section on the dashboard between "incoming reviews" and "recently closed": "CCed on". At the moment, it seems rview can't list such changes.

Could you please add a tab for that?

If you say you would accept this feature & would provide a few code pointers, I may look at doing this myself. :-)

Thanks,

Miklos

**Comment by jruesga** [comment]
Sorry, for delay to response.

https://github.com/jruesga/rview/commit/1841721e9a2ccaebba337815be71f3f6913b7c8d address the issue.

Regards.

**Comment by vmiklos** [comment]
Thanks a lot, this is great! Looking forward to test it in the next release. :-)
