### ISSUE TITLE
Comment filtering

### ISSUE THREAD

**Issue by dulek** [jruesga/rview#17]
I'm trying to use the app to review OpenStack code. This gets pretty difficult with openstack/cinder repositories, as we have ~60 CIs autocommenting on each patchset (for example see https://review.openstack.org/#/c/378658/). This makes reading review comments hard. I wonder if it would't be possible to add some configurable filter to filter comments based on username? In this particular case a "^.* CI$" regex would filter out all of the comments from CIs.

**Comment by jruesga** [comment]
This is an interesting feature. I wil check deeper to see if i can add a Toogle CI setting option (like the gerrit ui have) to show/hide CI comments.

**Comment by dulek** [comment]
FYI - this "Toggle CI" button is a feature added in OpenStack's Gerrit fork [1]. It works on client (browser) side.

[1] https://review.openstack.org/#/c/95743/

**Comment by jruesga** [comment]
3ac24bb3cbac31addbfa0cc4a464dd305c54e75d mimics the "Toggle CI" OpenStack button. It is opt out by default, so go to your account settings and activate "Toggle CI accounts messages" setting.
