### ISSUE TITLE
Deleted files of a commit can't be viewed if logged in

### ISSUE THREAD

**Issue by gmrt** [jruesga/rview#18]
If I'm logged in and I try to view the changes of a deleted file, the snackbar pops up with "Bad request" as message. This seems to happen only if I'm logged in.

Log: http://pastebin.com/raw/nEK1QLLp

**Comment by jruesga** [comment]
https://github.com/jruesga/rview/commit/0c2b4cf624de0987e95c146816390b2a9e83df6d

**Comment by gmrt** [comment]
Sorry, that wasn't even too far down in the history, I wonder how I missed it.
Well, thank you for the quick reply.
