### ISSUE TITLE
Links fail to open

### ISSUE THREAD

**Issue by lokal-profil** [jruesga/rview#19]
When I click on a gerrit link Android now suggests to open it in the app (thanks!).

Links such as `https://gerrit.wikimedia.org/r/#/c/332088/` and `https://gerrit.wikimedia.org/r/#/q/I13518d214811101ec2e592fd3491d41cd5f425eb` open fine but for the format `https://gerrit.wikimedia.org/r/332088` I get the message `Cannot handle link: com.ruesga.rview://changeid/r:332088`.

Unsure whether the failing format is due to some settings specifically to the wikimedia setup or if this applies generally. If the former then no worries.

**Comment by jruesga** [comment]
https://github.com/jruesga/rview/commit/a7abcf44627998cf2390ecdf1ea7b9be835cd7e1
