### ISSUE TITLE
Option to add reviewers after a patch is merged

### ISSUE THREAD

**Issue by TheCrazyLex** [jruesga/rview#22]
Gerrit offers support for adding reviewers after a patch is already merged.
That's useful if you want to notify someone of an already merged patch.

Would be cool if that could be integrated into the app :) 

Thank you!

**Comment by jruesga** [comment]
Implemeted in f1a76c8ca1b5f0a402d02fc322d4f53a94def1af

**Comment by TheCrazyLex** [comment]
Thank you!
