### ISSUE TITLE
[FEATURE] Add custom scopes to Side Bar

### ISSUE THREAD

**Issue by TimSchumi** [jruesga/rview#25]
I would really like the ability to add custom searches into the left-side bar

**Comment by jruesga** [comment]
You can do that in the current version. Just perform your custom search, then tap on the upper right icon and choose save (and give your custom search a friendly name). The custom search will be added to the left navigation menu and, in addition, you can also set it as a the default home page in settings.

**Comment by TimSchumi** [comment]
Sorry, never noticed the Save button. Thanks!
