### ISSUE TITLE
Sometimes wrong value for Code-Review score

### ISSUE THREAD

**Issue by jeremyfreudberg** [jruesga/rview#35]
Version 1.3.7 (and probably others, I'm new to this app)  

The first two reviews in the picture have a Code-Review+2, but shows as +1. Maybe due to the pacing of the votes? You can see the reviews here: https://review.openstack.org/#/c/465804/ and  https://review.openstack.org/#/c/453856/

![capture _2017-06-10-12-41-55](https://user-images.githubusercontent.com/16519305/27004659-d844f388-4dda-11e7-929e-5011c0702a1f.png)

**Comment by jruesga** [comment]
Thank you for the bug report. Fixed in https://github.com/jruesga/rview/commit/6cce4d38744c51908c2dd11c2d45acd977368ab4
