### ISSUE TITLE
Sometimes wrong Github avatar

### ISSUE THREAD

**Issue by jeremyfreudberg** [jruesga/rview#39]
https://github.com/jruesga/rview/blob/master/app/src/main/java/com/ruesga/rview/misc/ModelHelper.java#L180

I don't think that's a reliable way to find the user's Github avatar. I can provide at least one example of the wrong avatar being shown. However, I'm pretty sure there is no better way to do it.

**Comment by jruesga** [comment]
Yeah, I know there is not a direct match between Gerrit usernames and Github usernames but there is no way to obtain a github avatar by email (except using the rest api which requieres extra calls an probably a login/oauth process). Said the that Github is now the last avatar resource. See https://github.com/jruesga/rview/issues/13 for a previous discussion on this problem.

**Comment by jeremyfreudberg** [comment]
Thanks for the response. Sorry I missed digging up the prior issue about it.

Keep up the good work: I really enjoy this app.
