### ISSUE TITLE
Tab markup dropped halfway through file

### ISSUE THREAD

**Issue by lokal-profil** [jruesga/rview#41]
I ran across an issue today when the Rview diff view failed to show that the indentations were using tabs. The [same diff](https://gerrit.wikimedia.org/r/#/c/365563/3..4/tests/qunit/ext.wikispeech.test.js) viewed through gerrit successfully indicates all of the tabs.

![screenshot_20170825-094235](https://user-images.githubusercontent.com/4129218/29706631-c1c840f4-8982-11e7-824f-c5a0e64adfa6.png)

**Comment by jruesga** [comment]
Fixed in https://github.com/jruesga/rview/commit/0d237aa87828853b79b96820c8df064f34b8dd1b

Sorry for the noise this bug introduced.

**Comment by lokal-profil** [comment]
No worries. Thanks for the quick fix
