### ISSUE TITLE
Can't rebase the change

### ISSUE THREAD

**Issue by vlotorev** [jruesga/rview#44]
I'm having a change that is available to be rebased on gerrit web page. But it's not possible to rebase via Rview application
* click Rebase on change screen
* new popup window appears, the line for commit has text "Subject, change number, or leave empty"
* Rebase button is always blank, whether I fill commit or not. So rebase never can be performed.

**Comment by jruesga** [comment]
Fixed in https://github.com/jruesga/rview/commit/29e0df5f7809911c40135e614eda2eb281f87f29

You still need to unckeck the switch to enable the rebase button, but you can the parent empty (that is how it works in the Gerrit UI)

**Comment by vlotorev** [comment]
Great, thanks.
