### ISSUE TITLE
Lost edited comment on screen lock

### ISSUE THREAD

**Issue by vlotorev** [jruesga/rview#51]
It's quite easy to lose comment being edited:
* start edit comment
* lock the screen or get distracted for a moment and phone autolocks the screen
* unlock the screen but edited comment is lost

Expected behaviour:
* comment is not lost and ready to be continued

**Comment by jruesga** [comment]
Should be fixed by https://github.com/jruesga/rview/commit/5c0ddf8405b0b2fea93dfca64b1226a6107db475
