### ISSUE TITLE
Authenticated access (login) fails on review.typo3.org

### ISSUE THREAD

**Issue by neufeind** [jruesga/rview#55]
Rview reports the username is not valid.
Did they implement something special for review.typo3.org, besides the login-method gerrit uses by default?

**Comment by jruesga** [comment]
@neufeind  For authentication the Gerrit REST api doesn't use the same user and login than Gerrit web, but a generated http password. To obtain it, you must login in the typo3 gerrit instance and go to your profile settings. In tha page, there is a "http password" option in the left menu. Just click on genererate to obtain a password. To login with Rview just use the username and the generated password.
To simplify things, in the account wizard page of Rview there is a link that redirects to the http password page. You can generate the password and click y copy, so you can paste easy into the paasword field.

Let me know if that helps with your authentication problem.

**Comment by neufeind** [comment]
I didn't know there was a separate password, my bad.
Thank you very much for the prompt response and helping hand!
