### ISSUE TITLE
Non latin chars are mangled on editing file

### ISSUE THREAD

**Issue by vlotorev** [jruesga/rview#56]
I have UTF8 text file with non ascii characters in repository.

In case this file is viewed during review in app all characters are displayed ok.

In case I try editing this file in app then all characters are unreadable like improper encoding is used. Meanwhile all ascii characters are ok.

**Comment by jruesga** [comment]
Should be fixed in 9ae6ed4b00541388226da6b777f39fbfaf4f8160

**Comment by vlotorev** [comment]
Thanks, great.
