### ISSUE TITLE
Crash on editing file and landscape screen 

### ISSUE THREAD

**Issue by vlotorev** [jruesga/rview#57]
In case I try editing the file in app in portrait mode then only top half of the screen is displaying file contents. The bottom half is blank.

In case I rotate the phone in landscape mode the app crashes.

Android 6.0.1

**Comment by jruesga** [comment]
e5322919b4144e0448c4111187f9afbb9feb8398 fixes the wrong editor view layout (half blank).

**Comment by jruesga** [comment]
452d654af7a6ab6d64860b3877015e826cd73d18 fixes the rotation crash

**Comment by jruesga** [comment]
Thanks for the bug reports :)
