### ISSUE TITLE
Can't select text while editing

### ISSUE THREAD

**Issue by vlotorev** [jruesga/rview#65]
Issues seems to be relevant:
* after long tap on word text selection markers don't appear while 'cut/paste/copy/select all' pop up appears
* 'select all' action doesn't select the text at all.

**Comment by jruesga** [comment]
@vlotorev there is some issues still open related to IME and Ace Editor, an one remaining is still the copy/paste/select issues (https://github.com/ajaxorg/ace/issues?utf8=%E2%9C%93&q=android). I could try with other editors (like codemirror), but the last time I checked them they will have other issues as well, so I opted by Ace. I will try to check again, but for now i had no fix for this issue.

**Comment by jruesga** [comment]
With the latest commits in master (the last one is #c5e45b5d64944a1f0a1aff8c7609f8bc4a53b2e0) this behaviour should be fixed. I hacked the webview and the ace editor library to provide a fake selection dialog and selection handles that simulates the Android default one.

 @vlotorev in case you want to test it, this link (https://cloud.ruesga.com/f/52b4b4f964/) contains the Rview's version 2.2.0-beta1, which contains the patches described above.

**Comment by vlotorev** [comment]
@jruesga , I tested the build, now selicting the text works as expected, thanks.
