### ISSUE TITLE
Register .*/gerrit/.* URL for rview

### ISSUE THREAD

**Issue by vlotorev** [jruesga/rview#67]
Hi,

Clicking on URL link in Android opens suggestion popup with applications to open the link. 
It is possible to open links for gerrit.domain.com/* with rview and not possible to open links for domain.com/gerrit/*.

Is it possible to register URL for rview so that it would open domain.com/gerrit/* links with rview?

**Comment by jruesga** [comment]
Implemented in 4b4395c4c9bf6753c46dc5ffefba29d5277b7fc9

**Comment by vlotorev** [comment]
Great, thanks.
