### ISSUE TITLE
Crash on viewing profile

### ISSUE THREAD

**Issue by vlotorev** [jruesga/rview#69]
Reproduce:
* Open change https://gerrit-review.googlesource.com/#/c/104724 in the app.
* Scroll down to last comment from David Pursehouse with abandoning.
* Tap on David's avatar to view the profile.

**Comment by xenreon** [comment]
![screenshot_20180311-011824](https://user-images.githubusercontent.com/15876576/37246170-39524dee-24ca-11e8-9867-e356c95cbd76.png)
Well, looks fine here.

**Comment by jruesga** [comment]
@xenreon is a bug regresion in the master brach with the reviewer updates  new feature (@vlotorev is running a beta). I will fix it. Thanks for the report.

**Comment by jruesga** [comment]
Fixed in ce0141d07d8cded1d4f1fc41b12aed441eda6b53
