### ISSUE TITLE
Request to add draft (unpublished) comments view

### ISSUE THREAD

**Issue by vlotorev** [jruesga/rview#79]
Currently to list unpublished comments user has to use Gerrit web UI.

**Comment by jruesga** [comment]
@vlotorev i'm not sure what are you referring to. I just tested an it works properly (draft comments were listed and displayed correct).

![screenshot_20180605-231911](https://user-images.githubusercontent.com/1987507/41003561-51abe2d8-6917-11e8-9510-e07eed3552a6.png)
![screenshot_20180605-231918](https://user-images.githubusercontent.com/1987507/41003564-547c4eb2-6917-11e8-956a-cf12ee6c9e65.png)

I checked both ways (drafts created from gerrit ui and drafts creates from Rview).

Just tested with a development version of the master branch. Any related version of Gerrit i should check or you are taking about a different "unpublish comments" feature.

**Comment by jruesga** [comment]
Ok. I just understood your request.

**Comment by vlotorev** [comment]
I'm sorry for confusion. I meant list of changes that has unpublished comments. On the web UI it's available in My->Draft Comments view or by https://mygerrit/#/q/has:draft URL

**Comment by jruesga** [comment]
Implemented in 1e6d845f092b86e9485d3f1ba93266c2e84250fd
