### ISSUE TITLE
 What is Mute operation?

### ISSUE THREAD

**Issue by vlotorev** [jruesga/rview#84]
There are More-≥Mute and More->Mark as Reviewed actions in the drop down list on the CHANGE DETAILS area.

According to [1] Mute action has been replaced with Mark as reviewed before Gerrit 2.15 release.

Should not be Mute removed from the Rview?

I have gerrit 2.15.2 on server.

[1] https://gerrit-review.googlesource.com/#/c/129873

**Comment by jruesga** [comment]
Muite is related to https://gerrit-review.googlesource.com/Documentation/intro-user.html#ignore and relate to ignore/unignore operations https://gerrit-review.googlesource.com/Documentation/rest-api-changes.html#ignore

I will rename them. Thanks

**Comment by jruesga** [comment]
Fixed in c70e13788155b8b66d59346662a2a8ef6481aa87
