### ISSUE TITLE
"Show tagged" button is broken

### ISSUE THREAD

**Issue by vlotorev** [jruesga/rview#89]
* Open https://gerrit-review.googlesource.com/#/c/188870
* note there are messages with build job statuses from Gerrit Forge CI
* Tap "Hide tagged" button
* Tap "Show tagged" button
* Build job messages don't appear

The issue with Show CI button

**Comment by jruesga** [comment]
Fixed in b4cd616dd7d46cdbf873c733f7573fa1f82d4144
