### ISSUE TITLE
Bot comments are not shown

### ISSUE THREAD

**Issue by vlotorev** [jruesga/rview#98]
Open bot [comment](https://gerrit-review.googlesource.com/c/gerrit/+/222601/1/Documentation/cmd-set-reviewers.txt#33) in Rview - it's not rendered.
This commrnt is viewable if opened via browser.

Probably this comment is a Robot comment (see https://gerrit-review.googlesource.com/Documentation/config-robot-comments.html).

**Comment by jruesga** [comment]
Sorry for the delay to response.

Addressed in https://github.com/jruesga/rview/commit/8f25dfc92293c7d554edb88f560dc2e6f9381faf

**Comment by vlotorev** [comment]
Thanks for fixing and working on this great app!
