### ISSUE TITLE
Release a new version on android play store

### ISSUE THREAD

**Issue by evrardjp** [jruesga/rview#99]
Hello,

Could you release a new version of rview for the play store, please?

I am looking for this patch to get included: https://github.com/jruesga/rview/commit/fb4b50277b0a03f754b6832fefc6711116223826

Thanks.

**Comment by jruesga** [comment]
Sure, I will try to release a new version tonight.

**Comment by evrardjp** [comment]
Thanks a lot!

**Comment by jruesga** [comment]
Version 2.3.21 is rolling right now to the PlayStore. In the meantime, you can download it from releases https://github.com/jruesga/rview/releases/latest

**Comment by evrardjp** [comment]
Great, amazing, thanks for the work! :)
